server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: oauth-example-spring-boot-basic
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html

oauth:
  naver:
    client-id: ${NAVER_CLIENT_ID}
    client-secret: ${NAVER_CLIENT_SECRET}
    redirect-uri: http://localhost:${server.port}/oauth/callback/naver
    scope: profile,email
    authorize-endpoint: https://nid.naver.com/oauth2.0/authorize
    token-endpoint: https://nid.naver.com/oauth2.0/token
    profile-endpoint: https://openapi.naver.com/v1/nid/me

logging:
  level:
    root: INFO
    com.example.oauth: DEBUG
    org.scriptonbasestar.oauth: DEBUG
